name: ingrediente_seguro
description: Escanea ingredientes y descubre qué son los códigos E.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_ml_kit_text_recognition: ^0.11.0
  firebase_core: ^2.24.0
  cloud_firestore: ^4.17.0
  camera: ^0.10.6
  image_picker: ^1.0.7
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  generate: true
